### ISSUE TITLE
Not saving settings

### ISSUE THREAD

**Issue by flyingfishflash** [sissbruecker/linkding-extension#8] opened 2021-06-03 13:21 UTC
Perhaps this is by design, but after restarting firefox, the settings have been lost, and I have to re-enter the URL and API token. Kind of an inconvenience.

**Comment by sissbruecker** [comment] 2023-04-17 17:47
Not intended, but also not something I can reproduce. Maybe you are using some specific Firefox setting that clears the cache / local storage when closing the browser.

**Closed by sissbruecker** 2023-04-17 17:47 UTC
